# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  # OS selection
  config.vm.box = "centos/7"

  # Machine name
  config.vm.hostname = 'remediate'

  # To resolve later 11/08/2020
  # vagrant plugin install vagrant-disksize -> To define the size of the disk
  # config.disksize.size = '20GB'

  # Set VM name in VirtualBox
  config.vm.provider "virtualbox" do |v|
    v.name = 'Puppet Remediate'
    v.memory = 2048
    v.cpus = 2
  end

  # Configure second network
  config.vm.network "private_network", ip:"192.168.167.173" # EUREKAAA!!!

  # Copy public key from notebook
  config.vm.provision "file", source: "/Users/falvarez/.ssh/id_rsa.pub", destination: "$HOME/.ssh/public_notebook_key"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    cat /home/vagrant/.ssh/public_notebook_key >> /home/vagrant/.ssh/authorized_keys
    rm /home/vagrant/.ssh/public_notebook_key -rf
    #setenforce permissive
    #yum update -y
  SHELL
end
